language: python
sudo: required
before_install: sudo apt-get install povray libffi-dev imagemagick
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  # gifmaze examples
  - cd src/gifmaze/
  - python example_game_of_life.py
  - python example_hilbert_curve.py
  - python example_maze_animations.py
  - python example_ust.py
  # domino shuffling animation
  - cd ../aztec/
  - python run_domino_shuffling_animation.py
  # coupling from the past
  - cd ../cftp/
  - python main.py
  # aperiodic tilings
  - cd ../aperiodic-tilings/
  - python ammann-beenker.py
  - python debruijn.py
  - python penrose.py
  # Hopf fibration
  - cd ../hopf/
  - jupyter nbconvert --execute hopf_fibration.ipynb
  # miscellaneous examples
  - cd ../misc/
  - python mandelbrot.py
  - python julia.py
  - python newton.py
  - python modulargroup.py
  - python fractaltree.py
  - python e8.py
  - python kaleidoscope.py
  # polytopes examples
  - cd ../polytopes/
  - python run_polychora_examples.py
  - python run_3d_polyhedra_animation.py
  - python run_coset_enumeration.py tc_examples/G8723.yaml
  # travis-ci cannot run glsl and ffmpeg examples, so omit grayscott, mobius and lorenz examples.
