language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install Pillow
script:
  - cd src/gifmaze/
  - python example_embed_background_image.py
  - python example_hilbert_curve.py
  - python example_simple.py
  - python example_use_mask.py
  # - python example_ust.py  # fail in Python 2 due to matplotlib: _tkinter.TclError: no display name and no $DISPLAY environment variable
  - python example_with_solve.py
